### ISSUE TITLE
 Преобразователь уровня для матрицы

### ISSUE THREAD

**Issue by KarlHanz** [AlexGyver/BendeRadio#1]
Hi, Alex! В преобразователе уровня для матрицы нет необходимости, т.к. логическая единица трёх вольтовой логики для пяти вольтовой логики будет тоже являться логической единицей. Высоким уровнем для пяти вольтовой логики является уровень напряжения выше половины напряжения питания, низким - менее половины. Таким образом, логическая единица в 3,3В выше чем половина напряжения питания от 5В, т.е. более 2,5В, а логический ноль обычно всегда равен 0В в той и другой логике. 
На практике в одном моём проекте работает такое прямое подключение
![scheme](https://github.com/AlexGyver/BendeRadio/assets/35717905/9f37c673-0c29-44cd-8927-ed24f3d15baf)
!

**Comment by GyverLibs** [comment]
Я бы не стал добавлять конвертер, если бы без него работало. Ну и смотри даташит страница 3
